### ISSUE TITLE
env.Append(CFLAGS=["-S"])

### ISSUE THREAD

**Issue by ghost** [maxgerhardt/pio-stm8-dce#1]
I wanted to add env.Append(CFLAGS=["-S"]) but why does it not work correctly Is it a platformio glitch?

**Comment by maxgerhardt** [comment]
For just appending CFLAGS you could have also used 
```ini
build_flags = -S
```
however, as I reed the manual, this will just make the compiler output an annotated assembly file and stop compilation. I don't think you need this because all the generated assembly files are already also saved in `.pio/build/<env>/`.

**Comment by ghost** [comment]
> For just appending CFLAGS you could have also used
> 
> ```ini
> build_flags = -S
> ```
> 
> however, as I reed the manual, this will just make the compiler output an annotated assembly file and stop compilation. I don't think you need this because all the generated assembly files are already also saved in `.pio/build/<env>/`.

arigato
